---
- hosts: basilisk
  become: true
  tasks:
    - name: Update and upgrade of apt package.
      shell: apt update

    - name: Install latest version of maven.
      apt:
        name: maven
        state: latest
        update_cache: 'True'

    - name: CHeck Java
      command: java -version
      register: version
      ignore_errors: True
      
    - name: install Java
      apt: name=default-jdk state=present update_cache=yes force=yes
      when: "version != 0"

    - name: Install git
      apt: name=git state=present update_cache=yes

    - name: Download Basilisk.
      git:
        repo: https://github.com/ranjithmasthikatte/Basilisk.git
        dest: /BasiliskSourceRepository
        version: feature/DockerHook
                  
    - name: Maven build.
      shell: "mvn clean install"
      register: mvn_result
      args:
        chdir: /BasiliskSourceRepository

    - name: Create Basilisk root directory
      file:
        path: /Basilisk
        state: directory

    - name: Copy Basilisk jar file to root directory
      copy:
        src: /BasiliskSourceRepository/target/basilisk-1.0-SNAPSHOT.jar
        dest: /Basilisk/
        remote_src: yes
        mode: '0655'
